# Site settings
title: Ashish's Blog
email: ashish_0320@deerwalk.edu.np
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/demo"
url: "http://ashiish.github.io"
github_username:  Ashiish
facebook_username:  ashiish.khanal

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
